import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../src/styles/globals.scss";
import Footer from "@/src/components/molecules/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ForDoggoZ - An Initiative",
  description: "Generated by create next app",
  icons: "/svg/logo.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
